### ISSUE TITLE
Test and merge DS PR #1241 "NPE during SAF format import with collection files" as a module overlay

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#371]
I attempted to load a SAF batch using a "collections" file to load each item to multiple collections, as described in https://wiki.duraspace.org/display/DSDOC5x/Importing+and+Exporting+Items+via+Simple+Archive+Format. (Previously, I have only loaded to a single collection per batch and had not used the collections file.)

I received the error, 

```
Processing contents file: /dspace/assetstore/ingest/SimpleArchiveFormatBatchloads/20160809_10919_multi/item_1/contents
    Bitstream: 2009_faculty_survey_results_pp.pdf
Processing handle file: handle
It appears there is no handle file -- generating one
java.lang.NullPointerException
    at org.dspace.app.itemimport.ItemImport.addItem(ItemImport.java:938)
    at org.dspace.app.itemimport.ItemImport.addItems(ItemImport.java:736)
    at org.dspace.app.itemimport.ItemImport.main(ItemImport.java:498)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
    at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)
java.lang.NullPointerException
```

This issue was reported in [[DS-2633] NPE during SAF format import (ItemImport) with collections files](https://jira.duraspace.org/browse/DS-2633). It was fixed in pull request [NPE during SAF format import with collection files #1241](https://github.com/DSpace/DSpace/pull/1241) and is scheduled for inclusion DSpace 6.0.

Please create a module overlay that incorporates this change, test, and merge it.

**Comment by alawvt** [comment]
Resolved with PR #372.
