### ISSUE TITLE
Items not indexed on production

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#515]
At least one item, `http://hdl.handle.net/10919/74350`, is not indexed on production but is indexed on pprd, `https://vtechworks.pprd.lib.vt.edu/handle/10919/74350`, and dev, `https://vtechworks.dev.lib.vt.edu/handle/10919/74350`. On production, the All Faculty collection that contains it has an item count of 1235. The metadata for the collection lists 1239 items. I do not know (but am not certain) of any items in this collection that have been withdrawn which would cause this discrepancy.

Related older issue #357 might be useful for reference. I will ask @zoto724 to re-index.

**Comment by alawvt** [comment]
@arunkp7489  rebuilt the index last night but it apparently did not finish because the collection counts are still low.

**Comment by alawvt** [comment]
From /dspace/log/dspace.log.2017-11-27, here's an example of an item that was indexed
```
2017-11-27 18:30:14,161 INFO  org.dspace.discovery.SolrServiceImpl @ Wrote Item: 10919/65690 to Index
```
 and one that was not indexed,
```
2017-11-27 18:30:14,327 ERROR org.dspace.discovery.SolrServiceImpl @ Error while writing item to discovery index: 10919/73063 message:Expected mime type application/octet-stream but got application/xml. <?xml version="1.0" encoding="UTF-8"?>
<response>
<lst name="error"><str name="msg">Processing of multipart/form-data request failed. /tmp/tomcat7-tomcat7-tmp/upload_7f45faa5_15ffc1f9984__7fff_08696914.tmp (No such file or directory)</str><str name="trace">org.apache.commons.fileupload.FileUploadBase$IOFileUploadException: Processing of multipart/form-data request failed. /tmp/tomcat7-tomcat7-tmp/upload_7f45faa5_15ffc1f9984__7fff_08696914.tmp (No such file or directory)
	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:367)
	at org.apache.commons.fileupload.servlet.ServletFileUpload.parseRequest(ServletFileUpload.java:126)
	at org.apache.solr.servlet.SolrRequestParsers$MultipartRequestParser.parseParamsAndFillStreams(SolrRequestParsers.java:543)
	at org.apache.solr.servlet.SolrRequestParsers$StandardRequestParser.parseParamsAndFillStreams(SolrRequestParsers.java:679)
	at org.apache.solr.servlet.SolrRequestParsers.parse(SolrRequestParsers.java:146)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:398)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:207)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.dspace.solr.filters.LocalHostRestrictionFilter.doFilter(LocalHostRestrictionFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:315)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /tmp/tomcat7-tomcat7-tmp/upload_7f45faa5_15ffc1f9984__7fff_08696914.tmp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.&lt;init&gt;(FileOutputStream.java:213)
	at java.io.FileOutputStream.&lt;init&gt;(FileOutputStream.java:162)
	at org.apache.commons.io.output.DeferredFileOutputStream.thresholdReached(DeferredFileOutputStream.java:178)
	at org.apache.commons.io.output.ThresholdingOutputStream.checkThreshold(ThresholdingOutputStream.java:224)
	at org.apache.commons.io.output.ThresholdingOutputStream.write(ThresholdingOutputStream.java:128)
	at org.apache.commons.fileupload.util.Streams.copy(Streams.java:101)
	at org.apache.commons.fileupload.util.Streams.copy(Streams.java:64)
	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:362)
	... 26 more
</str><int name="code">500</int></lst>
</response>

org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: Expected mime type application/octet-stream but got application/xml. <?xml version="1.0" encoding="UTF-8"?>
<response>
<lst name="error"><str name="msg">Processing of multipart/form-data request failed. /tmp/tomcat7-tomcat7-tmp/upload_7f45faa5_15ffc1f9984__7fff_08696914.tmp (No such file or directory)</str><str name="trace">org.apache.commons.fileupload.FileUploadBase$IOFileUploadException: Processing of multipart/form-data request failed. /tmp/tomcat7-tomcat7-tmp/upload_7f45faa5_15ffc1f9984__7fff_08696914.tmp (No such file or directory)
	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:367)
	at org.apache.commons.fileupload.servlet.ServletFileUpload.parseRequest(ServletFileUpload.java:126)
	at org.apache.solr.servlet.SolrRequestParsers$MultipartRequestParser.parseParamsAndFillStreams(SolrRequestParsers.java:543)
	at org.apache.solr.servlet.SolrRequestParsers$StandardRequestParser.parseParamsAndFillStreams(SolrRequestParsers.java:679)
	at org.apache.solr.servlet.SolrRequestParsers.parse(SolrRequestParsers.java:146)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:398)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:207)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.dspace.solr.filters.LocalHostRestrictionFilter.doFilter(LocalHostRestrictionFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:315)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /tmp/tomcat7-tomcat7-tmp/upload_7f45faa5_15ffc1f9984__7fff_08696914.tmp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.&lt;init&gt;(FileOutputStream.java:213)
	at java.io.FileOutputStream.&lt;init&gt;(FileOutputStream.java:162)
	at org.apache.commons.io.output.DeferredFileOutputStream.thresholdReached(DeferredFileOutputStream.java:178)
	at org.apache.commons.io.output.ThresholdingOutputStream.checkThreshold(ThresholdingOutputStream.java:224)
	at org.apache.commons.io.output.ThresholdingOutputStream.write(ThresholdingOutputStream.java:128)
	at org.apache.commons.fileupload.util.Streams.copy(Streams.java:101)
	at org.apache.commons.fileupload.util.Streams.copy(Streams.java:64)
	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:362)
	... 26 more
</str><int name="code">500</int></lst>
</response>

	at org.apache.solr.client.solrj.impl.HttpSolrServer.executeMethod(HttpSolrServer.java:512)
	at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:210)
	at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:206)
	at org.apache.solr.client.solrj.request.AbstractUpdateRequest.process(AbstractUpdateRequest.java:124)
	at org.dspace.discovery.SolrServiceImpl.writeDocument(SolrServiceImpl.java:748)
	at org.dspace.discovery.SolrServiceImpl.buildDocument(SolrServiceImpl.java:1429)
	at org.dspace.discovery.SolrServiceImpl.indexContent(SolrServiceImpl.java:230)
	at org.dspace.discovery.SolrServiceImpl.updateIndex(SolrServiceImpl.java:410)
	at org.dspace.discovery.SolrServiceImpl.createIndex(SolrServiceImpl.java:370)
	at org.dspace.discovery.IndexClient.main(IndexClient.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)
```
The string, "Error while writing item to discovery index," occurs 37,412 times in this log.

**Comment by alawvt** [comment]
@arunkp7489, would you look at http://dspace.2283337.n4.nabble.com/filter-media-error-crashed-DSpace-td4686240.html and see if this might be an issue for us?  Thanks.

**Comment by alawvt** [comment]
As per the above issue, his /var is 100%. In our case we still have 25% free space. Also /var/cache/tomcat7/Catalina/localhost/_/cache-dir/cocoon-ehcache.data file referenced in the above issues is 1.7G in vtechworksprod box.

**Comment by alawvt** [comment]
The directory in the error message is /tmp/tomcat7-tomcat7-tmp/. `<lst name="error"><str name="msg">Processing of multipart/form-data request failed. /tmp/tomcat7-tomcat7-tmp/upload_7f45faa5_15ffc1f9984__7fff_08696914.tmp (No such file or directory)</str><str name="trace">org.apache.commons.fileupload.FileUploadBase$IOFileUploadException: Processing of multipart/form-data request failed. /tmp/tomcat7-tomcat7-tmp/upload_7f45faa5_15ffc1f9984__7fff_08696914.tmp (No such file or directory)`.

`/tmp/tomcat7-tomcat7-tmp/` does not exist.

ps -ax | grep java
```
yields
```
-Djava.io.tmpdir=/tmp/tomcat7-tomcat7-tmp
```
Here’s an issue, where the environmental variable was not being recognized, http://dspace.2283337.n4.nabble.com/Dspace-Java-heap-space-10-3-td4675775.html.
```
@arunkp7489 restarted Tomcat and now `/tmp/tomcat7-tomcat7-tmp/` does exist.

**Comment by alawvt** [comment]
Reindexing had no effect,
```sudo -u vtechworks /dspace/bin/dspace index-discovery -o
SOLR Search Optimize -- Process Started:1511886707147
SOLR Search Optimize -- Process Finished:1511886736981
SOLR Search Optimize -- Total time taken:29834 (ms).
```
with
```
Exception: Handle is null
org.dspace.discovery.SearchServiceException: Handle is null
        at org.dspace.discovery.SolrServiceImpl.cleanIndex(SolrServiceImpl.java:507)
        at org.dspace.discovery.IndexClient.main(IndexClient.java:126)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)
Caused by: java.lang.IllegalArgumentException: Handle is null
        at org.dspace.handle.HandleManager.findHandleInternal(HandleManager.java:532)
        at org.dspace.handle.HandleManager.resolveToObject(HandleManager.java:322)
        at org.dspace.discovery.SolrServiceImpl.cleanIndex(SolrServiceImpl.java:488)
        ... 7 more
```
So @arunkp7489, restarted DSpace and is running 
```
sudo -u vtechworks /dspace/bin/dspace index-discovery -b
```

**Comment by alawvt** [comment]
Indexing completed at 17:00. On production, the All Faculty collection now lists 1239 items, as expected.

There was one error in the log,
```
2017-11-28 16:17:45,996 ERROR org.dspace.discovery.SolrServiceImpl @ Error while writing item to discovery index: 10919/74976 message:org.apache.tika.exception.TikaException: Failed to parse an email message
org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: org.apache.tika.exception.TikaException: Failed to parse an email message
	at org.apache.solr.client.solrj.impl.HttpSolrServer.executeMethod(HttpSolrServer.java:552)
	at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:210)
	at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:206)
	at org.apache.solr.client.solrj.request.AbstractUpdateRequest.process(AbstractUpdateRequest.java:124)
	at org.dspace.discovery.SolrServiceImpl.writeDocument(SolrServiceImpl.java:748)
	at org.dspace.discovery.SolrServiceImpl.buildDocument(SolrServiceImpl.java:1429)
	at org.dspace.discovery.SolrServiceImpl.indexContent(SolrServiceImpl.java:230)
	at org.dspace.discovery.SolrServiceImpl.updateIndex(SolrServiceImpl.java:410)
	at org.dspace.discovery.SolrServiceImpl.createIndex(SolrServiceImpl.java:370)
	at org.dspace.discovery.IndexClient.main(IndexClient.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)
```
https://groups.google.com/forum/#!msg/dspace-tech/rFerEopaAjE/U_hBQS9PFwAJ might be relevant.

I am able to find this item by searching for either author or title. The issue above points to a problem with the text files. I have deleted these.

I am closing this issue because it seems now to be resolved. @arunkp7489 and @zoto724, thank you very much for your assistance.
