### ISSUE TITLE
SWORD deposit fails on https://vtechworks-rt2.dev.lib.vt.edu

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#516]
For testing Repository Tools 2 in Elements, @zoto724 created a redirect so https://vtechworks-rt2.dev.lib.vt.edu is an alternate URL for  https://vtechworks.dev.lib.vt.edu. This URL works. The URL,  https://vtechworks-rt2.dev.lib.vt.edu/REST, also works. However, the [SWORDv2](https://wiki.duraspace.org/display/DSDOC5x/SWORDv2+Server) and [SWORD](https://wiki.duraspace.org/display/DSDOC5x/SWORDv1+Server) commands do not work.
```
curl -i  https://vtechworks.dev.lib.vt.edu/sword/servicedocument --user "dspace-elements-rt2-g@vt.edu"

HTTP/1.1 200 OK
```
```
curl -i  https://vtechworks.dev.lib.vt.edu/swordv2/servicedocument --user "dspace-elements-rt2-g@vt.edu"

HTTP/1.1 200 OK
```
```
curl -i  https://vtechworks-rt2.dev.lib.vt.edu/sword/servicedocument --user "dspace-elements-rt2-g@vt.edu"


HTTP/1.1 400 Bad Request
Date: Mon, 04 Dec 2017 17:54:49 GMT
Server: Apache-Coyote/1.1
Content-Type: text/html;charset=utf-8
Content-Language: en
Content-Length: 1208
Connection: close
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Content-Type-Options: nosniff
X-Content-Security-Policy: default-src https:; script-src https: 'unsafe-inline' 'unsafe-eval'; style-src https: 'unsafe-inline'; img-src https: data: ; font-src https: data:
Content-Security-Policy: default-src https:; script-src https: 'unsafe-inline' 'unsafe-eval'; style-src https: 'unsafe-inline'; img-src https: data: ; font-src https: data:
X-Frame-Options: DENY

Apache Tomcat/7.0.52 (Ubuntu) - Error report
HTTP Status 400 - Unable to recognise URL as a valid service document: http://vtechworks-rt2.dev.lib.vt.edu/sword/servicedocument

type Status report

message Unable to recognise URL as a valid service document: http://vtechworks-rt2.dev.lib.vt.edu/sword/servicedocument

description The request sent by the client was syntactically incorrect.
```
```
curl -i  https://vtechworks-rt2.dev.lib.vt.edu/swordv2/servicedocument --user "dspace-elements-rt2-g@vt.edu"
Enter host password for user 'dspace-elements-rt2-g@vt.edu':
HTTP/1.1 400 Bad Request
Date: Mon, 04 Dec 2017 18:04:19 GMT
Server: Apache-Coyote/1.1
Content-Type: text/xml;charset=UTF-8
Connection: close
Transfer-Encoding: chunked
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Content-Type-Options: nosniff
X-Content-Security-Policy: default-src https:; script-src https: 'unsafe-inline' 'unsafe-eval'; style-src https: 'unsafe-inline'; img-src https: data: ; font-src https: data:
Content-Security-Policy: default-src https:; script-src https: 'unsafe-inline' 'unsafe-eval'; style-src https: 'unsafe-inline'; img-src https: data: ; font-src https: data:
X-Frame-Options: DENY

<?xml version="1.0" encoding="ISO-8859-1"?>
<sword:error href="http://www.dspace.org/ns/sword/2.0/errors/BadUrl" xmlns:sword="http://purl.org/net/sword/terms/"><atom:title xmlns:atom="http://www.w3.org/2005/Atom">ERROR</atom:title><atom:updated xmlns:atom="http://www.w3.org/2005/Atom">2017-12-04T13:04:19Z</atom:updated><atom:generator uri="http://www.dspace.org/ns/sword/2.0/" version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">vtechworks@vt.edu</atom:generator><sword:treatment>Processing failed</sword:treatment><atom:summary xmlns:atom="http://www.w3.org/2005/Atom">Unable to recognise URL as a valid service document: http://vtechworks-rt2.dev.lib.vt.edu/swordv2/servicedocument</atom:summary><sword:verboseDescription>org.swordapp.server.SwordError: Unable to recognise URL as a valid service document: http://vtechworks-rt2.dev.lib.vt.edu/swordv2/servicedocument
	at org.dspace.sword2.SwordUrlManager.extractDSpaceObject(SwordUrlManager.java:304)
	at org.dspace.sword2.ServiceDocumentManagerDSpace.getServiceDocument(ServiceDocumentManagerDSpace.java:142)
	at org.dspace.sword2.ServiceDocumentManagerDSpace.getServiceDocument(ServiceDocumentManagerDSpace.java:60)
	at org.swordapp.server.ServiceDocumentAPI.get(ServiceDocumentAPI.java:56)
	at org.swordapp.server.servlets.ServiceDocumentServletDefault.doGet(ServiceDocumentServletDefault.java:32)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:315)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</sword:verboseDescription><atom:link rel="alternate" type="text/html" href="http://localhost:8080/xmlui/contact" xmlns:atom="http://www.w3.org/2005/Atom"/></sword:error>
```

**Comment by alawvt** [comment]
As @keithgee mentioned, please see #493 since a similar fix will probably be needed for the alternative URL, vtechworks-rt2.lib.vt.edu.

**Comment by alawvt** [comment]
It is not possible to enable SWORD or SWORDv2 for both vtechworks.dev.lib.vt.edu and vtechworks-rt2.dev.lib.vt.edu. 

As noted in https://code.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/sword, Therefore, 
**2017-12-08 Temporary Configuration: 
SWORD is only enabled for vtechworks.dev.lib.vt.edu, not vtechworks-rt2.dev.lib.vt.edu. SWORDv2 is only enabled for vtechworks-rt2.dev.lib.vt.edu, not vtechworks.dev.lib.vt.edu.** 

>In `dspace/config/modules/swordv2-server.cfg`, replace `servicedocument.url = http://vtechworks.dev.lib.vt.edu/swordv2/servicedocument` 
with `servicedocument.url = http://vtechworks-rt2.dev.lib.vt.edu/swordv2/servicedocument`.

Thank you, @zoto724!

**Comment by alawvt** [comment]
- `curl -i  https://vtechworks-rt2.dev.lib.vt.edu/swordv2/servicedocument --user "dspace-elements-rt2-g@vt.edu"` - result: service document returned

- `curl -i https://vtechworks-rt2.dev.lib.vt.edu/swordv2/collection/10919/80948 --data-binary "@art_4959256494595851995.zip" -H "Content-Disposition: filename=art_4959256494595851995.zip" -H "Content-Type: application/zip" -H "Packaging: http://purl.org/net/sword/package/METSDSpaceSIP" --user "dspace-elements-rt2-g@vt.edu"` - result: 404 Not Found

**Should be disabled?**
- `curl -i  https://vtechworks.dev.lib.vt.edu/swordv2/servicedocument --user "dspace-elements-rt2-g@vt.edu"` - result: 400 Bad Request

- `curl -i https://vtechworks.dev.lib.vt.edu/swordv2/collection/10919/80948 --data-binary "@art_4959256494595851995.zip" -H "Content-Disposition: filename=art_4959256494595851995.zip" -H "Content-Type: application/zip" -H "Packaging: http://purl.org/net/sword/package/METSDSpaceSIP" --user "dspace-elements-rt2-g@vt.edu"` - result: 201 Created (success)

**Comment by alawvt** [comment]
Because of this problem which is not easily resolved, @zoto724 would like to move both the SWORD and SWORDv2 configuration back to vtechwork.dev and eliminate the vtechworks-rt2.dev URL. Testing on vtechworks.dev would only be for RT2, not RT1.

**Comment by alawvt** [comment]
We have configured RT2 but not RT1 to work on vtechworks.dev.lib.vt.edu. Settings are documented in https://code.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/Elements_Repository_Tools_2.
