### ISSUE TITLE
Investigate why thumbnails are not created after running filter-media

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#547]
@pyc1 reported that thumbnails were not generated this morning. I ran manually, `sudo -u vtechworks /dspace/bin/dspace filter-media`

For http://hdl.handle.net/10919/85312, a text file was created but not a thumbnail. dspace.log.2018-10-09 contains 
```
File: HORT-12.pdf.txt
FILTERED: bitstream 324458 (item: 10919/85312) and created 'HORT-12.pdf.txt'
File: HORT-12.pdf.jpg
ERROR filtering, skipping bitstream:

	Item Handle: 10919/85312
	Bundle Name: ORIGINAL
	File Size: 119605
	Checksum: 79e4cc0abab14ef9efdc38a7657be9bc (MD5)
	Asset Store: 0
org.im4java.core.CommandException: org.im4java.core.CommandException: convert-im6.q16: not authorized `/tmp/impdfthumb3260432555236643183.pdf' @ error/constitute.c/ReadImage/412.
org.im4java.core.CommandException: org.im4java.core.CommandException: convert-im6.q16: not authorized `/tmp/impdfthumb3260432555236643183.pdf' @ error/constitute.c/ReadImage/412.
	at org.im4java.core.ImageCommand.run(ImageCommand.java:219)
	at org.dspace.app.mediafilter.ImageMagickThumbnailFilter.getImageFile(ImageMagickThumbnailFilter.java:153)
	at org.dspace.app.mediafilter.ImageMagickPdfThumbnailFilter.getDestinationStream(ImageMagickPdfThumbnailFilter.java:24)
	at org.dspace.app.mediafilter.MediaFilterManager.processBitstream(MediaFilterManager.java:734)
	at org.dspace.app.mediafilter.MediaFilterManager.filterBitstream(MediaFilterManager.java:550)
	at org.dspace.app.mediafilter.MediaFilterManager.filterItem(MediaFilterManager.java:500)
	at org.dspace.app.mediafilter.MediaFilterManager.applyFiltersItem(MediaFilterManager.java:468)
	at org.dspace.app.mediafilter.MediaFilterManager.applyFiltersAllItems(MediaFilterManager.java:403)
	at org.dspace.app.mediafilter.MediaFilterManager.main(MediaFilterManager.java:340)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)
Caused by: org.im4java.core.CommandException: convert-im6.q16: not authorized `/tmp/impdfthumb3260432555236643183.pdf' @ error/constitute.c/ReadImage/412.
	at org.im4java.core.ImageCommand.finished(ImageCommand.java:253)
	at org.im4java.process.ProcessStarter.run(ProcessStarter.java:314)
	at org.im4java.core.ImageCommand.run(ImageCommand.java:215)
	... 14 more
```

**Comment by soumikgh** [comment]
So, due to a [code execution bug](https://lists.ubuntu.com/archives/bionic-changes/2018-October/016634.html) in GhostScript, ImageMagick, in its latest update, disabled the processing of a lot of file formats, including PDFs. Based on [this diff](http://launchpadlibrarian.net/390771456/imagemagick_8%3A6.7.7.10-6ubuntu3.12_8%3A6.7.7.10-6ubuntu3.13.diff.gz) and [this StackOverflow answer](https://stackoverflow.com/a/52661288/1146918), I undid the changes on `/etc/ImageMagick-6/policy.xml`. This will probably be rolled back on a later version of ImageMagick once the vulnerabilities are fixed.

**Comment by keithgee** [comment]
Wow, that was very quick work by both of you to find a resolution to a problem that we hadn't seen in VTechWorks before now!

**Comment by alawvt** [comment]
@soumikgh, thank you very much for troubleshooting and modifying the policy. The issue was reported today on the DSpace Tech listserv, https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/dspace-tech/2O4WnzIEcl8.
