### ISSUE TITLE
VTechWorks Handle server not resolving due to lock file

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#707]
The VTechWorks handle server is not resolving. 

attempted to restart it  with the error, 
```
"2020/06/29 11:34:51 EDT" 25 Rotating log files
Error: Queue files are locked
       (see the error log for details.)
Shutting down...
```
The /dspace/bin/start-handle-server was erroring out with "Queue files are locked" in `/dspace/log/handle-server.log`. @soumikgh found this ticket, https://jira.lyrasis.org/browse/DS-3946; renamed the lock file at /dspace/handle-server/txns/lock, and only then was able to successfully start up the Handle Server.

**Comment by alawvt** [comment]
```
Error: lock file (/dspace/handle-server/txns/lock) exists.  If you are sure that another server is not running, remove this file and restart the server
java.lang.Exception: Queue files are locked
        at net.handle.server.TransactionQueue.getLock(TransactionQueue.java:230)
        at net.handle.server.TransactionQueue.<init>(TransactionQueue.java:110)
        at net.handle.server.HandleServer.<init>(HandleServer.java:493)
        at net.handle.server.AbstractServer.getInstance(AbstractServer.java:72)
        at net.handle.server.Main.initialize(Main.java:152)
        at net.handle.server.Main.main(Main.java:75)
Shutting down...
```
And it's resolved by deleting the lockfile.
